/* ═══════════════════════════════════════════════════════════
   science content + source registry
   Every factual statement rendered in the UI is keyed to an entry
   in SOURCES. If a claim has no source, it is not written as fact.
   URLs here were verified live on 2026-09-28.
   ═══════════════════════════════════════════════════════════ */

export const ACCESSED = '2026-09-28';

/* ── Source registry ────────────────────────────────────────
   tier:    INSTITUTE | AGENCY | REVIEW | TEXTBOOK | TECH DOC
   kind:    DOCUMENTED (published finding) | CONCEPTUAL (our model)
   ─────────────────────────────────────────────────────────── */
export const SOURCES = {
  /* ── Real 3D assets, with the licences they require ── */
  assetNasaSuit: {
    id: 'assetNasaSuit',
    title: 'Advanced Crew Escape Suit (3D model)',
    org: 'NASA 3D Resources',
    tier: 'AGENCY',
    url: 'https://science.nasa.gov/3d-resources/advanced-crew-escape-suit/',
    pub: 'Model dated 20 March 2025',
    topics: ['spaceflight', 'anatomy', 'assets'],
    summary: 'The full-pressure Advanced Crew Escape Suit, published by NASA as a downloadable GLB. The NASA 3D Resources repository states that its assets are "free and without copyright"; usage follows the NASA Images and Media Usage Guidelines.',
    supports: 'The real suit mesh used for the floating astronaut and the standing measurement figure, replacing the procedural placeholder.',
    used: ['Hero — floating astronaut', '02 Body — measurement figure'],
    licence: 'Public domain (NASA) — https://www.nasa.gov/nasa-brand-center/images-and-media',
    asset: './assets/models/nasa-aces-suit.glb',
  },
  assetNihBrain: {
    id: 'assetNihBrain',
    title: 'Detailed Human Brain Model (3D model)',
    org: 'NIH 3D (entry 3DPX-021161)',
    tier: 'INSTITUTE',
    url: 'https://3d.nih.gov/entries/3DPX-021161',
    pub: 'Created 11 May 2024 · published 24 March 2025',
    topics: ['brain', 'anatomy', 'assets'],
    summary: 'A detailed anatomical human brain mesh published on NIH 3D by the contributor "Johnson J", built after the method in Hyes, A.G. (2018), Production of 3D Printed Scale Models from Microscope Volume Datasets.',
    supports: 'The real anatomical brain mesh behind the pathway visualisation in section 04, replacing the stylised hemispheres.',
    used: ['04 Brain — anatomical mesh'],
    licence: 'CC-BY 4.0 — https://creativecommons.org/licenses/by/4.0/ — attribution required and given here',
    attribution: 'Model by Johnson J, via NIH 3D (3DPX-021161), licensed CC-BY 4.0.',
    asset: './assets/models/nih-brain.glb',
  },

  nidcdBalance: {
    id: 'nidcdBalance',
    title: 'Balance Disorders',
    org: 'NIH / NIDCD',
    tier: 'INSTITUTE',
    url: 'https://www.nidcd.nih.gov/health/balance-disorders',
    pub: 'NIH Pub. No. 00-4374 — last updated March 6, 2018',
    topics: ['vestibular', 'anatomy', 'balance', 'otolith', 'canals'],
    summary: 'Plain-language institutional fact sheet covering how the body keeps balance, the anatomy of the labyrinth, cupula and otoconia mechanics, otolith organ function, and how balance disorders are tested.',
    supports: 'Anatomy and mechanics of the semicircular canals, cupula, stereocilia, utricle, saccule and otoconia. The three-input model of balance (vision, vestibular, musculoskeletal). Clinical test names including posturography, rotational chair and head-shaking tests.',
    used: ['Ear model labels', 'Body section — three sensory inputs', 'Gravity section — otolith explanation', 'Hero spec cards'],
  },
  nidcdGlossary: {
    id: 'nidcdGlossary',
    title: 'Vestibular System (glossary entry)',
    org: 'NIH / NIDCD',
    tier: 'INSTITUTE',
    url: 'https://www.nidcd.nih.gov/glossary/vestibular-system',
    pub: 'Accessed ' + ACCESSED,
    topics: ['vestibular', 'definition'],
    summary: 'Institutional definition: the system responsible for maintaining balance, posture and the body\'s orientation in space, which also regulates locomotion and keeps objects in visual focus as the body moves.',
    supports: 'The definition of the vestibular system and its three functional roles — balance, orientation, gaze stabilisation.',
    used: ['Hero section framing', 'Ear section intro'],
  },
  statpearlsVestibularPathways: {
    id: 'statpearlsVestibularPathways',
    title: 'Neuroanatomy, Vestibular Pathways',
    org: 'StatPearls / NCBI Bookshelf',
    tier: 'TEXTBOOK',
    url: 'https://www.ncbi.nlm.nih.gov/books/NBK557380/',
    pub: 'Updated 8 Nov 2025',
    pubmed: 'https://pubmed.ncbi.nlm.nih.gov/32491312/',
    topics: ['brain', 'pathways', 'brainstem', 'cerebellum', 'cortex'],
    summary: 'Peer-reviewed textbook chapter describing the central vestibular pathways: the vestibular nerve, the vestibular nuclei in the brainstem, cerebellar modulation, and the thalamo-cortical projections that produce conscious perception of orientation.',
    supports: 'The central pathway sequence used in the Brain section — eighth nerve → vestibular nuclei → cerebellum → thalamus → cortex. Cerebellar role in calibrating and adapting vestibular reflexes.',
    used: ['Brain model stages', 'Brain section pathway list', 'Signal-loop diagram'],
  },
  nasaSensorimotorRisk: {
    id: 'nasaSensorimotorRisk',
    title: 'Risk of Altered Sensorimotor/Vestibular Function Impacting Critical Mission Tasks, Human Health, and Long-Term Health',
    org: 'NASA Human Research Program',
    tier: 'AGENCY',
    url: 'https://humanresearchroadmap.nasa.gov/Risks/risk.aspx?i=88',
    pub: 'Risk page; HSRB-approved rating 11/2024',
    topics: ['spaceflight', 'microgravity', 'risk'],
    summary: 'NASA\'s formal risk entry. States that altered gravity changes sensorimotor and vestibular function in ways that can produce motion sickness, spatial disorientation, reduced postural control and locomotion, and manual and fine-motor deficits — and that the risk of impairment is greatest during and soon after gravity transitions.',
    supports: 'The spaceflight framing used throughout: why weightlessness changes orientation, why transitions matter, and the operational framing around landing, egress and early EVA.',
    used: ['Space section framing', 'Timeline phases', 'Intro copy'],
  },
  nasaSensorimotorHub: {
    id: 'nasaSensorimotorHub',
    title: 'Sensorimotor Risk',
    org: 'NASA (Office of the Chief Health and Medical Officer / HHP)',
    tier: 'AGENCY',
    url: 'https://www.nasa.gov/directorates/esdmd/hhp/sensorimotor-risk/',
    pub: 'Byline 11 March 2025',
    topics: ['spaceflight', 'microgravity', 'risk'],
    summary: 'NASA\'s public summary of the sensorimotor risk, including the statement that impairment risk is greatest during and soon after gravity transitions, when performance decrements may have high operational impact — manual landings, immediate egress after landing, and early EVAs.',
    supports: 'The specific operational framing around gravity transitions, and the DAG/narrative downloads referenced on that page.',
    used: ['Space section — gravity transition explanation'],
  },
  nasaDagNarrative: {
    id: 'nasaDagNarrative',
    title: 'Sensorimotor Risk — Directed Acyclic Graph narrative',
    org: 'NASA Human Research Program',
    tier: 'AGENCY',
    url: 'https://www.nasa.gov/wp-content/uploads/2025/07/sensorimotor-dag-narrative.pdf',
    pub: 'DAG dated 25 June 2025',
    topics: ['spaceflight', 'risk', 'framework'],
    summary: 'NASA\'s published causal model for the sensorimotor risk, expressed as a directed acyclic graph with contributing factors, associated risks and outcomes.',
    supports: 'The structure of our adaptation timeline — our phases follow NASA\'s cause-to-outcome ordering rather than an arbitrary sequence.',
    used: ['Timeline structure', 'docs/SOURCES.md'],
  },
  nasaTechPort157166: {
    id: 'nasaTechPort157166',
    title: 'Sensorimotor Countermeasures',
    org: 'NASA TechPort (Mars Campaign Office)',
    tier: 'AGENCY',
    url: 'https://techport.nasa.gov/projects/157166',
    pub: 'Project period 2020-10-01 → 2025-09-30',
    topics: ['spaceflight', 'countermeasures', 'metrics'],
    summary: 'NASA project record covering sensorimotor countermeasures, including an "Unobtrusive Monitoring Tools and Operational Assessments" sub-project whose stated objective is to quantify sensorimotor adaptation after gravity transitions and define sensorimotor performance metrics.',
    supports: 'Our justification for building a monitoring and awareness layer rather than claiming to invent vestibular measurement. The metric framework we present is aligned with a need NASA has documented.',
    used: ['Research page', 'docs/SCIENCE.md'],
  },
  cipherVestibularHealth: {
    id: 'cipherVestibularHealth',
    title: 'Neuro-Vestibular Examination During and Following Spaceflight (Vestibular Health)',
    org: 'NASA — JSC / NSL, CIPHER programme',
    tier: 'AGENCY',
    url: 'https://ntrs.nasa.gov/citations/20230014013',
    pub: 'HRP Investigators\' Workshop 2024',
    topics: ['spaceflight', 'vestibular', 'eye-tracking'],
    summary: 'CIPHER Vestibular Health study protocol: records eye, head and body movement during and after spaceflight, and uses OpenCV-based 3-D eye tracking as part of the examination.',
    supports: 'Evidence that camera-based eye and head measurement is established practice in flight vestibular research — the same signal class this site visualises with commodity hardware.',
    used: ['Sensor section framing', 'Research page'],
  },
  cipherVhit: {
    id: 'cipherVhit',
    title: 'Comparison of Active and Passive Head Impulse Testing (vHIT)',
    org: 'NASA — NSL, CIPHER Vestibular Health',
    tier: 'AGENCY',
    url: 'https://ntrs.nasa.gov/citations/20230014322',
    pub: 'HRP Investigators\' Workshop poster',
    topics: ['spaceflight', 'vor', 'vestibular'],
    summary: 'Compares active and passive video head impulse testing to quantify the vestibulo-ocular reflex, and reports that standard passive head-impulse methodology is feasible in spaceflight.',
    supports: 'The VOR section: that VOR gain is an actively measured quantity in flight vestibular research, and that head-impulse style testing is practical in that setting.',
    used: ['VOR section', 'Lab — VOR demonstration source'],
  },
  nasaNeuroVestibularIws25: {
    id: 'nasaNeuroVestibularIws25',
    title: 'Neuro-Vestibular Examination During and Following Spaceflight',
    org: 'NASA — NSL, HRP Investigators\' Workshop 2025',
    tier: 'AGENCY',
    url: 'https://ntrs.nasa.gov/api/citations/20250000348/downloads/IWS25%20Neuro-Vestibular.pdf',
    pub: '2025',
    topics: ['spaceflight', 'vestibular', 'motion-sickness'],
    summary: 'Conference material noting that spaceflight-induced sensorimotor adaptations can cause neurological disturbances mediated by the vestibular system, including space motion sickness and spatial disorientation.',
    supports: 'Wording for the space section on space motion sickness and spatial disorientation.',
    used: ['Space section', 'Lab — visual-vestibular conflict source'],
  },
  nasaMotionSicknessCountermeasures: {
    id: 'nasaMotionSicknessCountermeasures',
    title: 'Evaluation of Motion Sickness Countermeasures (Inscop)',
    org: 'NASA — NSL, HRP Investigators\' Workshop 2025',
    tier: 'AGENCY',
    url: 'https://ntrs.nasa.gov/api/citations/20250000739/downloads/NSL_IWS25_Widhalm_Inscop_Poster.pdf',
    pub: '2025',
    topics: ['spaceflight', 'motion-sickness', 'questionnaire'],
    summary: 'Poster describing motion sickness countermeasure evaluation, and noting that the motion sickness questionnaire has been incorporated into Spaceflight Standard Measures and the CIPHER Vestibular Health experiment.',
    supports: 'That structured symptom self-report is a real instrument in flight research — the basis for our wording that questionnaires are part of standard measures.',
    used: ['Lab — motion direction recognition source', 'docs/SCIENCE.md'],
  },
  ntrsSensorimotorCountermeasures: {
    id: 'ntrsSensorimotorCountermeasures',
    title: 'Sensorimotor Countermeasures — technical report',
    org: 'NASA — NTRS',
    tier: 'AGENCY',
    url: 'https://ntrs.nasa.gov/citations/20240008210',
    pub: '2024',
    topics: ['spaceflight', 'countermeasures'],
    summary: 'Technical report record for the sensorimotor countermeasures work, distributed publicly (Distribution: Public).',
    supports: 'Public availability of the countermeasures programme this site draws on.',
    used: ['Research page', 'docs/SOURCES.md'],
  },
  cipherProgram: {
    id: 'cipherProgram',
    title: 'About CIPHER',
    org: 'NASA Human Research Program',
    tier: 'AGENCY',
    url: 'https://www.nasa.gov/reference/about-cipher/',
    pub: 'Programme reference page',
    topics: ['spaceflight', 'programme'],
    summary: 'Overview of CIPHER (Complement of Integrated Protocols for Human Exploration Research), NASA\'s integrated human-research programme covering multiple physiological systems including vestibular health.',
    supports: 'Programme context for the flight research cited elsewhere on this site.',
    used: ['Research page'],
  },
};

export const SOURCE_LIST = Object.values(SOURCES);

/* ── Ear structures ─────────────────────────────────────── */
export const EAR_STRUCTURES = [
  {
    id: 'canals',
    name: 'Semicircular Canals',
    short: 'Three fluid-filled ducts, one per plane.',
    senses: 'Angular acceleration (rotation)',
    detail: 'Three fluid-filled ducts forming loops arranged roughly at right angles to one another. Together they cover rotation in all three planes, so any turn of the head is detected by at least one canal.',
    mech: 'Head rotation → fluid lags behind → cupula deflects → stereocilia bend → nerve signal.',
    sources: ['nidcdBalance'],
  },
  {
    id: 'anterior',
    name: 'Anterior Canal',
    short: 'Senses rotation in the sagittal plane.',
    senses: 'Nodding / pitching rotation',
    detail: 'The anterior (superior) canal lies roughly in the sagittal plane and responds when the head pitches — nodding forward and back.',
    mech: 'Pitch rotation drives endolymph flow through the anterior duct.',
    sources: ['nidcdBalance'],
  },
  {
    id: 'posterior',
    name: 'Posterior Canal',
    short: 'Senses rotation about the front-back axis.',
    senses: 'Rolling / tilting rotation',
    detail: 'The posterior canal is oriented roughly in the frontal/parasagittal plane and responds to rolling or lateral tilting of the head.',
    mech: 'Roll rotation drives endolymph flow through the posterior duct.',
    sources: ['nidcdBalance'],
  },
  {
    id: 'lateral',
    name: 'Lateral (Horizontal) Canal',
    short: 'Senses horizontal head turning.',
    senses: 'Yaw rotation — turning the head left and right',
    detail: 'The lateral canal sits roughly in the horizontal plane. It is the primary detector for the left-right head turn that drives the horizontal vestibulo-ocular reflex.',
    mech: 'Yaw rotation drives endolymph flow through the lateral duct, producing the strongest signal of the three during a horizontal head shake.',
    sources: ['nidcdBalance', 'cipherVhit'],
  },
  {
    id: 'cupula',
    name: 'Cupula',
    short: 'The gel sail that blocks each canal and bends the hairs.',
    senses: 'Indirectly — it is the transducer between fluid and cells',
    detail: 'A gelatin-like structure stretched across one end of each canal like a thick sail, sitting on a cluster of sensory hair cells whose stereocilia project into it.',
    mech: 'Fluid movement makes the cupula flex or billow like a sail in the wind, which bends the stereocilia beneath it.',
    sources: ['nidcdBalance'],
  },
  {
    id: 'haircells',
    name: 'Hair Cells & Stereocilia',
    short: 'The mechanosensory cells that convert motion into nerve signals.',
    senses: 'Mechanical deflection of their stereocilia',
    detail: 'Sensory cells whose fine extensions, called stereocilia, project into the overlying gel. Bending the stereocilia is what generates the signal — the receptor is mechanical, not chemical or electrical.',
    mech: 'Stereocilia bending → receptor cell depolarisation → signal to the vestibular nerve.',
    sources: ['nidcdBalance'],
  },
  {
    id: 'utricle',
    name: 'Utricle',
    short: 'Otolith organ — horizontal linear acceleration and tilt.',
    senses: 'Linear acceleration and head tilt (roughly horizontal plane)',
    detail: 'One of two otolithic organs: a fluid-filled pouch with hair cells lining its floor, their stereocilia extending into a gel layer that contains dense calcium-carbonate grains called otoconia.',
    mech: 'Gravity (and linear acceleration) pulls on the otoconia, which displace the gel and bend the stereocilia, signalling head position and movement to the brain.',
    sources: ['nidcdBalance'],
  },
  {
    id: 'saccule',
    name: 'Saccule',
    short: 'Otolith organ — vertical linear acceleration.',
    senses: 'Vertical linear acceleration and head position relative to gravity',
    detail: 'The second otolithic organ, lying between the canals and the cochlea. Like the utricle it uses otoconia-loaded gel to report position with respect to gravity and any direction of head movement — side to side, up or down, forward or backward.',
    mech: 'Otoconia displacement under gravity or linear acceleration bends the stereocilia of the underlying hair cells.',
    sources: ['nidcdBalance'],
  },
  {
    id: 'otoconia',
    name: 'Otoconia',
    short: 'Calcium-carbonate grains that gravity pulls on.',
    senses: '— (they are the inertial mass that does the sensing)',
    detail: 'Tiny, dense grains of calcium carbonate embedded in the gel layer above the hair cells of the utricle and saccule. Whatever the position of the head, gravity pulls on them.',
    mech: 'Otoconia move → gel displaces → stereocilia bend → position signal reaches the brain.',
    sources: ['nidcdBalance'],
  },
  {
    id: 'nerve',
    name: 'Vestibular Nerve',
    short: 'The eighth cranial nerve — the output cable.',
    senses: '— (carries signals outward)',
    detail: 'The vestibular division of the eighth cranial (vestibulocochlear) nerve carries signals from the canals and otolith organs to the vestibular nuclei in the brainstem.',
    mech: 'Hair-cell signal → vestibular nerve → brainstem vestibular nuclei.',
    sources: ['nidcdBalance', 'statpearlsVestibularPathways'],
  },
];

/* which canal dominates for a given dominant rotation axis */
export const CANAL_AXIS_MAP = [
  { id: 'lateral', axis: 'yaw', label: 'LATERAL / YAW' },
  { id: 'anterior', axis: 'pitch', label: 'ANTERIOR / PITCH' },
  { id: 'posterior', axis: 'roll', label: 'POSTERIOR / ROLL' },
];

/* ── Brain pathway stages ───────────────────────────────── */
export const BRAIN_STAGES = [
  {
    id: 'nerve',
    name: 'Vestibular Nerve',
    role: 'Peripheral input',
    detail: 'The eighth cranial nerve delivers signals from the canals and otolith organs into the brainstem.',
    latency: 'First synapse',
    confidence: 'Well established',
    sources: ['statpearlsVestibularPathways', 'nidcdBalance'],
  },
  {
    id: 'nuclei',
    name: 'Vestibular Nuclei (Brainstem)',
    role: 'First central relay',
    detail: 'The primary central processing station. Signals arriving here are distributed to reflex circuits — including those driving eye muscles — and to ascending pathways.',
    latency: 'Milliseconds',
    confidence: 'Well established',
    sources: ['statpearlsVestibularPathways'],
  },
  {
    id: 'cerebellum',
    name: 'Cerebellum',
    role: 'Calibration & adaptation',
    detail: 'The cerebellum continuously tunes vestibular reflexes, including the vestibulo-ocular reflex, adjusting their gain as conditions change. It is the structure most associated with vestibular adaptation.',
    latency: 'Ongoing, not a single pass',
    confidence: 'Well established',
    sources: ['statpearlsVestibularPathways'],
  },
  {
    id: 'thalamus',
    name: 'Thalamus',
    role: 'Relay to cortex',
    detail: 'Vestibular information destined for conscious perception is routed through thalamic nuclei on its way to cortical areas.',
    latency: 'Relay',
    confidence: 'Established; individual nuclei studied in detail',
    sources: ['statpearlsVestibularPathways'],
  },
  {
    id: 'cortex',
    name: 'Cortical Networks',
    role: 'Perception & integration',
    detail: 'Cortical regions combine vestibular input with vision and proprioception to produce the conscious sense of orientation and self-motion. The exact map of these areas is more complex and less settled than the lower stages.',
    latency: 'Tens to hundreds of ms',
    confidence: 'Active research; area functions overlap and are not fully settled',
    sources: ['statpearlsVestibularPathways'],
  },
];

/* ── Gravity environments ───────────────────────────────── */
export const GRAVITIES = [
  {
    id: 'EARTH', label: 'EARTH', g: 1, short: '1 g',
    otolith: 1, float: 0,
    note: 'Reference condition. Otoconia are loaded continuously, giving the brain a stable “down”.',
    sources: ['nidcdBalance'],
  },
  {
    id: 'MOON', label: 'MOON', g: 0.166, short: '~0.16 g',
    otolith: 0.17, float: 0.78,
    note: 'About one sixth of Earth\'s gravitational acceleration. Otolith loading is much reduced, so the “down” signal is weaker.',
    sources: [],
    conceptual: true,
  },
  {
    id: 'MARS', label: 'MARS', g: 0.379, short: '~0.38 g',
    otolith: 0.38, float: 0.58,
    note: 'About 38% of Earth\'s gravitational acceleration. Otolith loading is reduced but clearly present.',
    sources: [],
    conceptual: true,
  },
  {
    id: 'MICROGRAVITY', label: 'MICROGRAVITY', g: 0, short: '~0 g',
    otolith: 0, float: 1,
    note: 'The constant gravitational load disappears. The canals still detect rotation normally — but the steady signal that told the brain which way was down goes quiet.',
    sources: ['nasaSensorimotorRisk', 'nasaSensorimotorHub'],
  },
];

/* ── Adaptation timeline ────────────────────────────────── */
export const TIMELINE = [
  {
    id: 'earth', n: '01', label: 'EARTH', kind: 'doc',
    title: 'Baseline',
    body: 'On Earth the vestibular system operates under a constant 1 g load. Otolith organs give a continuous reference for “down”, and the canals report rotation. The brain has learned to trust both.',
    sources: ['nidcdBalance'],
  },
  {
    id: 'launch', n: '02', label: 'LAUNCH', kind: 'doc',
    title: 'Transition and unloading',
    body: 'During ascent the vestibular system encounters sustained linear acceleration and then a rapid unloading. NASA identifies gravity transitions as the period of greatest impairment risk.',
    sources: ['nasaSensorimotorRisk', 'nasaSensorimotorHub'],
  },
  {
    id: 'early', n: '03', label: 'EARLY SPACEFLIGHT', kind: 'doc',
    title: 'Space motion sickness and spatial disorientation',
    body: 'Adaptations induced by spaceflight can produce neurological disturbances mediated by the vestibular system, including space motion sickness and spatial disorientation.',
    sources: ['nasaNeuroVestibularIws25'],
  },
  {
    id: 'adapt', n: '04', label: 'ADAPTATION', kind: 'doc',
    title: 'Sensory re-weighting',
    body: 'With the gravito-inertial reference altered, the brain increasingly relies on vision and proprioception. Vestibular reflexes are recalibrated — the cerebellum is heavily involved in tuning their gain.',
    sources: ['nasaSensorimotorRisk', 'statpearlsVestibularPathways'],
  },
  {
    id: 'long', n: '05', label: 'LONG EXPOSURE', kind: 'doc',
    title: 'Established microgravity state',
    body: 'Over long durations the adapted state becomes the new baseline. This is precisely why flight research uses within-subject comparison — the astronaut is their own reference.',
    sources: ['nasaTechPort157166'],
  },
  {
    id: 'return', n: '06', label: 'RETURN TO GRAVITY', kind: 'doc',
    title: 'Re-adaptation, and why transitions matter',
    body: 'Coming back means re-adapting to a gravity load the brain has stopped expecting. NASA states the risk of impairment is greatest during and soon after gravity transitions — manual landings, immediate egress after landing, and early EVAs.',
    sources: ['nasaSensorimotorRisk', 'nasaSensorimotorHub'],
  },
  {
    id: 'monitor', n: '07', label: 'MONITORING', kind: 'mod',
    title: 'What this site does, and does not, claim',
    body: 'This site visualises the mechanisms and lets you interact with them. It does not measure your vestibular function, and it does not predict performance. Those capabilities require validated, calibrated measurement and clinical interpretation.',
    sources: [],
    conceptual: true,
  },
];

/* ── Body section: sensory weighting ────────────────────── */
export const SENSORY_INPUTS = [
  { id: 'vision', label: 'VISION', min: 0, max: 100, def: 45, help: 'Dominant when inputs conflict — the main reason motion sickness occurs.' },
  { id: 'vestibular', label: 'VESTIBULAR', min: 0, max: 100, def: 40, help: 'Reports head rotation and linear acceleration. No off switch.' },
  { id: 'proprioception', label: 'PROPRIOCEPTION', min: 0, max: 100, def: 35, help: 'Muscle, joint and pressure sensors reporting load and surface contact.' },
];

/* ── Lab: six demonstrations ────────────────────────────── */
export const LAB_TESTS = [
  {
    id: 'orientation',
    n: 'TEST 01',
    name: 'Orientation Tracking',
    blurb: 'Track a moving target with head motion; observe tracking error accumulate.',
    what: 'Your tracking error over time while a target moves in a pattern you must follow.',
    why: 'Tracking combines a predictive component (the brain anticipates the target) with a feedback component (the eyes correct residual error). When the pattern becomes unpredictable, the predictive contribution collapses and error grows.',
    how: 'Vestibular, visual and proprioceptive signals are combined by the brainstem and cerebellum, which also receives a copy of the motor command. That internal model is what allows smooth prediction.',
    metrics: ['meanError', 'peakError', 'lagMs'],
    sources: ['statpearlsVestibularPathways', 'nidcdBalance'],
    mode: 'manual',
    conceptual: true,
  },
  {
    id: 'vor',
    n: 'TEST 02',
    name: 'VOR Demonstration',
    blurb: 'Sweep head rotation frequency; see where the reflex can no longer keep up.',
    what: 'Head angular velocity against the eye velocity the reflex can generate, across a sweep of frequencies.',
    why: 'The reflex behaves like a high-pass filter: excellent at fast head movements, weaker at very slow ones, where the visual system increasingly takes over. Above a certain frequency the reflex reaches a velocity ceiling.',
    how: 'A three-neuron arc links the canals to the eye muscles. Head rotation increases firing on one side and decreases it on the other, driving the eyes in the opposite direction. The cerebellum continuously adjusts the gain.',
    metrics: ['gain', 'phaseLagMs', 'cutoffHz'],
    sources: ['cipherVhit', 'statpearlsVestibularPathways', 'nidcdBalance'],
    mode: 'sweep',
    conceptual: true,
  },
  {
    id: 'balance',
    n: 'TEST 03',
    name: 'Balance & Axes Simulation',
    blurb: 'Watch a modelled centre of pressure wander as you widen the support base.',
    what: 'A simulated centre-of-pressure path as the base of support changes — a stability model, not a force-plate recording.',
    why: 'Balance behaves like an inverted pendulum. A wider base tolerates more sway before correction is needed; a narrow base means smaller disturbances produce larger excursions.',
    how: 'The brainstem integrates vestibular, visual and proprioceptive input and issues postural corrections. When inputs conflict, correction is delayed and sway amplitude grows.',
    metrics: ['swayPath', 'rmsAmplitude', 'ellipseArea'],
    sources: ['nidcdBalance', 'nasaSensorimotorRisk'],
    mode: 'stochastic',
    conceptual: true,
  },
  {
    id: 'motion',
    n: 'TEST 04',
    name: 'Motion Direction Recognition',
    blurb: 'Identify the direction of a short motion burst; measure reaction time.',
    what: 'Reaction time and accuracy when a brief motion burst appears in a random direction.',
    why: 'Detection speed depends on how rapidly the stimulus exceeds threshold against ongoing baseline activity. Brief stimuli near threshold produce slower and less accurate responses.',
    how: 'Structured motion-symptom self-report and directional perception tasks are used in flight research; the motion sickness questionnaire is part of Spaceflight Standard Measures and the CIPHER Vestibular Health experiment.',
    metrics: ['accuracy', 'medianRtMs', 'rtSpreadMs'],
    sources: ['nasaMotionSicknessCountermeasures', 'nasaNeuroVestibularIws25'],
    mode: 'trial',
    conceptual: true,
  },
  {
    id: 'conflict',
    n: 'TEST 05',
    name: 'Visual–Vestibular Conflict',
    blurb: 'Feed conflicting visual and inertial information; see the discomfort model rise.',
    what: 'A modelled conflict index as visual-optokinetic flow is pitted against the inertial signal.',
    why: 'Sickness is widely modelled as arising when two sensory systems disagree about self-motion. More mismatch means more conflict, and the model rises faster the longer the mismatch persists.',
    how: 'The brain compares an expected sensory consequence of movement against what it actually receives. Persistent mismatch triggers the autonomic responses associated with motion sickness.',
    metrics: ['conflictIndex', 'onsetEstimateS', 'cumulativeDose'],
    sources: ['nasaNeuroVestibularIws25', 'nasaMotionSicknessCountermeasures'],
    mode: 'ramp',
    conceptual: true,
  },
  {
    id: 'gravity',
    n: 'TEST 06',
    name: 'Earth vs Microgravity',
    blurb: 'Compare otolith loading and canal response side by side.',
    what: 'A side-by-side comparison of constant otolith load and rotation signal in 1 g versus weightlessness.',
    why: 'Rotation detection is essentially unchanged — the canals respond to angular motion regardless of gravity. What changes is the constant linear reference. Losing a steady “down” signal forces the brain to re-weight toward vision.',
    how: 'NASA characterises the impairment risk as greatest during and soon after gravity transitions, with high operational impact around manual landing, immediate egress and early EVA.',
    metrics: ['otolithLoad', 'rotationSignal', 'reweightingIndex'],
    sources: ['nasaSensorimotorRisk', 'nasaSensorimotorHub', 'nidcdBalance'],
    mode: 'compare',
    conceptual: true,
  },
];

/* ── Research page filters ──────────────────────────────── */
export const RESEARCH_TOPICS = [
  { id: 'all', label: 'ALL' },
  { id: 'vestibular', label: 'VESTIBULAR SYSTEM' },
  { id: 'anatomy', label: 'ANATOMY' },
  { id: 'brain', label: 'BRAIN & PATHWAYS' },
  { id: 'balance', label: 'BALANCE' },
  { id: 'vor', label: 'VOR' },
  { id: 'spaceflight', label: 'SPACEFLIGHT' },
  { id: 'microgravity', label: 'MICROGRAVITY' },
  { id: 'motion-sickness', label: 'MOTION SICKNESS' },
  { id: 'countermeasures', label: 'COUNTERMEASURES' },
];

export function findSource(id) { return SOURCES[id] || null; }
export function sourcesOf(ids = []) { return ids.map(findSource).filter(Boolean); }
